### PR TITLE
Commit msg error

### LINKED ISSUE #19: Print commit message on failure
It would be useful to the commit hook to print out the commit message along with the fact that you had an error. The main reason behind this is most people will think their commit message is lost and have to type it again (which sucks if you write a descriptive commit message). It is available under `.git/COMMIT_EDITMSG`, but most people aren't going to think to look there.

so instead of:

```bash
$ git commit [type some long commit message in the editor]
$ Error: Must commit against at least one issue.
```

We get:

```bash
$ git commit [type some long commit message in the editor]
$ Commit Message:
This is a long commit message

that will be printed on multiple lines so you can easily copy
/ paste back into the editor and add a jira issue to.
Error: Must commit against at least one issue.
```

### PR DESCRIPTION
**Pull request by Stran6**
-Outputs user commit message with error message for user convenience

Closes #19

### CODE REVIEW

File: src/precommit-entry.js [hunk 1]
```diff
@@ -42,6 +43,9 @@ export function precommit(path) {
   return getCommitMsg(path)
     .then(() => 0)
     .catch(err => {
+      console.log('Commit Message:');
+      console.log(fs.readFileSync(path, {encoding: 'utf8'}));
```
Comment (mtscout6) [inline src/precommit-entry.js]: This will be the second time reading this same file within this process. Perhaps you could carry over the first time you read it?

File: src/precommit-entry.js [hunk 2]
```diff
@@ -33,9 +33,12 @@ export function getCommitMsg(path) {
       fsp.readFile(path, {encoding: 'utf8'})
     ])
     .then(([projectKey, fileContents]) => {
+      commitMsg = fileContents;
        let issues = getIssueReference(fileContents, projectKey);
        return issueHandler.issueStrategizer(issues, jiraAPI);
-    });
+    })
+    .catch(error => Promise.reject(`Commit Message:\n${commitMsg}\n${error}`
```
Comment (mtscout6) [inline src/precommit-entry.js]: By doing this you are bypassing all the error formatting below. Would probably make sense to merge the two functions together now.

**Comment by mtscout6** [comment]
Odd that this test still passes: https://github.com/TWExchangeSolutions/jira-precommit-hook/blob/14c3d56ab8bc08da2ca3b2a60033a6db20b7d191/test/precommit-entry-test.js#L49

**Comment by mtscout6** [comment]
LGTM
